ObKo/stm32-cmake

- cmake/FindSTM32HAL.cmake
Component names for STM32F2 HAL are misspelled.
> Bugfix: misspelled STM32F2 peripherals names.

- cmake/ChibiOS16_HAL.cmake
Fixed a missing ChibiOS file causing link errors when using serial_usb module.
> Fixed a missing ChibiOS file 

- cmake/FindSTM32HAL.cmake
- stm32-blinky/stm32l0xx_hal_conf.h
FindSTM32HAL.cmake had no section to find HAL components for the L0 family.
I added the section and added the HAL header file to the blinky example.
> Added missing L0 section to find HAL components

- cmake/gcc_stm32f4.cmake
The F411 support is incomplete : according to the documentation, the regex should be `411.[CE]` instead of `411.[ED]`.
http://www.st.com/en/microcontrollers/stm32f411.html?querycriteria=productId=LN1877
> Fixed F411 support

- cmake/FindSTM32HAL.cmake
- cmake/FindSTM32LL.cmake
I exported inclusion of LL components to separated FindSTM32LL.cmake and removed possibility to add LL components using STM32HAL package. I checked datasheets to search which LL components are available for each supported family. There are also some components which are implemented only using header file and it is also taken into account within FindSTM32LL.cmake.
> Support LL library

- cmake/FindSTM32LL.cmake
It looks like USB is missing in the list of HAL LL components for STM32F1 series controller. This component is required when using HAL PCD components (stm32f1xx_hal_pcd.h is including stm32f1xx_ll_usb.h, at least for STM Cube V1.1.0 14-April-2017)
> Adding LL USB component for F1 controllers

- cmake/gcc_stm32f3.cmake
Add `-fno-builtin` and other flags that were only set for C++.
Specifically, adding `-fno-builtin` fixes some undefined reference to some `math.h` functiosn such as `ceil`, `floor` and `round`, when the link time optimizer is activated (with `-flto` flag).
> Fix gcc_stm32f3.cmake

- cmake/FindFATFS.cmake
In the standard Cube STM firmware there are only template driver files in the FatFS middleware, device specific driver files exist only in example etc. If the FatFS source is being taken from such a source then the cmake will now not fail but will prompt the user that they must manually include/source the device specific FatFS files.
> Handling of driver files not existing in standard STM firmware

- cmake/FindSTM32HAL.cmake
I was experiencing following issue:
```
CMake Error at CMakeLists.txt:66 (ADD_EXECUTABLE):
Cannot find source file:
HAL_stm32f1xx_hal_spi_ex_c_FILE-NOTFOUND
Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
.hpp .hxx .in .txx
```
There is no `_ex.c` file for SPI in https://github.com/STMicroelectronics/STM32CubeF1/tree/master/Drivers/STM32F1xx_HAL_Driver/Src.
> Fix HAL_stm32f1xx_hal_spi_ex_c_FILE-NOTFOUND for F1 family

- cmake/FindUSBHost.cmake
Was used to build the BSP example camera applications for the STM324xG_EVAL.
Not complete but a solid start.
> Rough implementation of USB host

- examples/blinky/CMakeLists.txt
- examples/custom-linker-script/CMakeLists.txt
- examples/template/CMakeLists.txt
- tests/bsp/CMakeLists.txt
- tests/cmsis/CMakeLists.txt
- tests/hal/CMakeLists.txt
I have not explicitly tested each example and each test if it fails with CMake < 3.13. I just saw one failing and then adjusted all occurrences.
> target_compile_options() needs CMake 3.13

- cmake/FindSTM32HAL.cmake
Proposed solution for https://github.com/ObKo/stm32-cmake/issues/148 to allow cmake builds for F7 boards.
> remove LL components for F7 builds

- README.md
There is a small typo in README.md.
Should read `similar` rather than `similiar`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, similiar -> similar

- README.md
TOOLCHAIN_PREFIX is no longer used, the correct name is now STM32_TOOLCHAIN_PATH. Let's make it easier for the next one who wants to update to the latest cmake environment.
> Correct outdated variable "TOOLCHAIN_PREFIX" name in readme file

- README.md
- cmake/FindHAL.cmake
This closes #177.
As added in the Readme.md, the [find_package documentation](https://cmake.org/cmake/help/v3.13/command/find_package.html?highlight=find%20package#id4) explains the behavior of this parameter.
> Retrieve hal version

- README.md
- cmake/stm32/common.cmake
- For MCUs with very little flash, the Nano standard library is more suitable.
- This change supports building with the GCC nano stdlib, simply by
linking STM32::Nano library in cmake.
> Adds support for the Newlib-Nano Standard Library

- cmake/stm32/common.cmake
- examples/blinky-ll/CMakeLists.txt
- examples/blinky/CMakeLists.txt
- examples/custom-linker-script/CMakeLists.txt
- examples/fetch-cmsis-hal/CMakeLists.txt
- examples/fetch-cube/CMakeLists.txt
- examples/freertos/CMakeLists.txt
- examples/multi-core/CMakeLists.txt
- examples/template/CMakeLists.txt
closes #166 
The function is called `stm32_print_size_of_target`
I also added a small modification so that STM32_TOOLCHAIN_PATH could be set by CMAKE_C_COMPILER. As a VScode user, this is how the compiler is passed to cmake.
> print binary size

- cmake/stm32/common.cmake
Merge after #182 , extends it with more modern CMake syntax with all lower-case letters
> Updated size command 

- cmake/FindBSP.cmake
Using
```
find_package(BSP COMPONENTS 
YOU BOARD
REQUIRED)
```
caused the bsp interface libraries to all have the same source files since the find file variable was the same between each iteration of the board components. This fixes this issue.
See [this issue](https://github.com/ObKo/stm32-cmake/issues/198) for more information.
> fixed find by board component

- README.md
- cmake/stm32/common.cmake
Functions to generate binary file and hex file
> added binary and hex generation functions

- cmake/stm32/utilities.cmake
Closes #228 . This makes some optimization flags optional. There is also the option to remove them altogether. If they are not removed, I might add some documentation.
I also removed the enforcement of optimization flags for build configurations
> utilities.cmake update default build flags

- examples/blinky-ll/CMakeLists.txt
- examples/blinky/CMakeLists.txt
- examples/custom-linker-script/CMakeLists.txt
- examples/fetch-cmsis-hal/CMakeLists.txt
- examples/fetch-cube/CMakeLists.txt
- examples/freertos/CMakeLists.txt
- examples/multi-core/CMakeLists.txt
- examples/template/CMakeLists.txt
- tests/bsp/CMakeLists.txt
- tests/cmsis/CMakeLists.txt
- tests/fetch/CMakeLists.txt
- tests/hal/CMakeLists.txt
> update minimum cmake version to 3.16

- cmake/FindHAL.cmake
When in H7 want to use HCD `HAL::STM32::H7::M7::HCD`, it returns error
```
CMake Error at test/CMakeLists.txt:1 (add_executable):
Target "test" links to target "HAL::STM32::H7::M7::HCD" but the target was                                                                                                                   
not found.  Perhaps a find_package() call is missing for an IMPORTED                                                                                                                         
target, or an ALIAS target is missing? 
```
Signed-off-by: Agis Zisimatos <agzisim@gmail.com>
> Add missing target for H7

- README.md
- cmake/FindCMSIS.cmake
- cmake/FindFreeRTOS.cmake
- cmake/stm32/devices.cmake
- examples/freertos/CMakeLists.txt
- examples/freertos/FreeRTOSConfig.h
- examples/freertos/main.cpp
- examples/freertos/main.h
- examples/freertos/stm32f4xx_hal_conf.h
- examples/freertos/stm32h7xx_hal_conf.h
Full discussion and review can be found here: https://github.com/ObKo/stm32-cmake/pull/227 . This is the squashed version of the feature for a cleaner history and with a proper git commit for the PR.
This branch has the complete feature set for CMSIS RTOS support.
Builds on #190 and #189 , a lot of work provided by @g-arjones , extended with documentation and an updated `freertos` example with the same architetecture as #225
Closes #227 
Closes #188 . Closes #160 issues
Closes #190 Closes #189 PR
The updated `freertos` example can now be compiled with CMSIS RTOS by passing `-DUSE_CMSIS_RTOS=ON` and CMSIS RTOSV2 by passing `-DUSE_CMSIS_RTOS_V2=ON` . When doing this, it is not necessary to set `FREERTOS_PATH` anymore, because the build system can use the FreeRTOS and CMSIS RTOS sources …
> CMSIS RTOS Feature

- README.md
- cmake/FindFreeRTOS.cmake
- examples/freertos/CMakeLists.txt
- examples/freertos/FreeRTOSConfig.h
- examples/freertos/main.cpp
- examples/freertos/stm32l5xx_hal_conf.h
#231
`ARM_CM23_NTZ` should behave like `ARM_CM4F` as there is no trust zone support
`ARM_CM23/secure` is a new target `ARM_CM23::secure`
`ARM_CM23/non_secure`  is a new target `ARM_CM23::non_secure` 
I plan to at least test the CM33_NTZ port on an L5 nucleo
The trust zone port will likely not be fully tested
> find_package(freeRTOS) for cortex M33 

- README.md
- cmake/FindCMSIS.cmake
The PR #287 points out that not enabling ASM language result in corrupted state.
> FindCMSIS checks that ASM is enabled before generating ASM related targets

- examples/blinky-ll/blinky.c
- examples/blinky/blinky.c
- examples/blinky/blinky.cpp
In #193, it was discovered that __WFI can lead to unwanted sleep of the device.
This is the fix proposed by @atsju
> Replaced __WFI with active infinite loop

- cmake/stm32_gcc.cmake
Warn the user if the CMake version is less than 3.16. Fix for issue #298
> Check cmake version and warn user if lower than required

- cmake/FindHAL.cmake
This pull request solves issue #307 for me;
I am not experienced with complex CMake and this particular toolchain, but hopefully, this is a generic fix.
closes #307
> Set lowercase family string in step 2 of find_package(HAL ...);

- cmake/stm32/common.cmake
After cmake 3.10 the target property OUTPUT_NAME is not set by default. This commit adds a check to see if the target property has a value.
> stm32: common: Fix '_stm32_generate_file'

- README.md
`CMSIS::STM32::<TYPE>` adds to target the `system_stm32f<family>xx.c` file. This file is not added by the `CMSIS::STM32::<FAMILY>` target and should be noted in the readme.
> feat: added reference to system_stm32f<family>xx in CMSIS targets

- cmake/stm32/utilities.cmake
The latest U5 STM32 Cube FW Package is 1.3.0. The CMSIS provided by STM matches the Cube version, as does the HAL.
> Update U5 to latest STM32 Cube FW Package

- cmake/stm32/utilities.cmake
According to https://htmlpreview.github.io/?https://github.com/STMicroelectronics/STM32CubeU5/blob/master/Release_Notes.html the CMSIS version is 1.3.1 and the HAL is 1.4.0.
> Update U5 to latest Cube 1.4.0

- cmake/stm32/utilities.cmake
Latest released Cube version is v1.28.0: https://htmlpreview.github.io/?https://github.com/STMicroelectronics/STM32CubeF4/blob/master/Release_Notes.html
It uses HAL version 1.8.2 and CMSIS version 2.6.9
> Update to use latest Cube / HAL / CMSIS for F4

- .github/workflows/cmake.yml
- .github/workflows/create-matrix.yml
In the objective of getting more contribution, these changes create the family matrix at CI run time.
I will be easier for a non CI-friendly contributor to add a new family to project as they won't have to make change in the workflow files.
Updating the Test workflow was the opportunity to update the deprecated checkout action step.
> Dynamic family matrix for CI jobs
